---
- name: SSH Pubkey-Drop
  hosts: offloader
  tags:
    - ssh
    - sshd
    - ssh-keys
  roles:
    - ssh-authorized-keys

# PREPARE: BECOME A SUDOER FIRST!
- name: Auxiliary Tools
  hosts: offloader
  tags:
    - tools
    - cli-tools
  roles:
    - cli-tools
