---
- name: SSH Pubkey-Drop
  hosts: offloader
  tags:
    - ssh
    - sshd
    - ssh-keys
  roles:
    - ssh-authorized-keys

# PREPARE: BECOME A SUDOER FIRST!
- name: Install Auxiliary Tools
  hosts: offloader
  tags:
    - tools
    - cli-tools
  roles:
    - cli-tools

- name: Install Docker and Unifi Controller
  hosts: offloader
  tags:
    - docker
    - unifi
  roles:
    - docker-unifi

- name: Install WireGuard and connect to FFMUC
  hosts: offloader
  tags:
    - wireguard
  roles:
    - wg-ffmuc

- name: Install vxlan
  hosts: offloader
  tags:
    - vxlan
  roles:
    - vxlan-ffmuc

